"""
Dota 2 Hero ID to Name Mapping
Used to convert numeric hero IDs from Clarity parser to readable hero names
"""

HERO_MAP = {
    1: "npc_dota_hero_antimage",
    2: "npc_dota_hero_axe",
    3: "npc_dota_hero_bane",
    4: "npc_dota_hero_bloodseeker",
    5: "npc_dota_hero_crystal_maiden",
    6: "npc_dota_hero_drow_ranger",
    7: "npc_dota_hero_earthshaker",
    8: "npc_dota_hero_juggernaut",
    9: "npc_dota_hero_mirana",
    10: "npc_dota_hero_morphling",
    11: "npc_dota_hero_nevermore",
    12: "npc_dota_hero_phantom_lancer",
    13: "npc_dota_hero_puck",
    14: "npc_dota_hero_pudge",
    15: "npc_dota_hero_razor",
    16: "npc_dota_hero_sand_king",
    17: "npc_dota_hero_storm_spirit",
    18: "npc_dota_hero_sven",
    19: "npc_dota_hero_tiny",
    20: "npc_dota_hero_vengefulspirit",
    21: "npc_dota_hero_windranger",
    22: "npc_dota_hero_zuus",
    23: "npc_dota_hero_kunkka",
    25: "npc_dota_hero_lina",
    26: "npc_dota_hero_lion",
    27: "npc_dota_hero_shadow_shaman",
    28: "npc_dota_hero_slardar",
    29: "npc_dota_hero_tidehunter",
    30: "npc_dota_hero_witch_doctor",
    31: "npc_dota_hero_lich",
    32: "npc_dota_hero_riki",
    33: "npc_dota_hero_enigma",
    35: "npc_dota_hero_sniper",
    36: "npc_dota_hero_necrolyte",
    37: "npc_dota_hero_warlock",
    38: "npc_dota_hero_beastmaster",
    39: "npc_dota_hero_queenofpain",
    40: "npc_dota_hero_venomancer",
    41: "npc_dota_hero_faceless_void",
    42: "npc_dota_hero_skeletal_king",
    43: "npc_dota_hero_death_prophet",
    44: "npc_dota_hero_phantom_assassin",
    45: "npc_dota_hero_pugna",
    46: "npc_dota_hero_templar_assassin",
    47: "npc_dota_hero_ogre_magi",
    48: "npc_dota_hero_night_stalker",
    49: "npc_dota_hero_techies",
    50: "npc_dota_hero_broodmother",
    51: "npc_dota_hero_bounty_hunter",
    52: "npc_dota_hero_weaver",
    53: "npc_dota_hero_jakiro",
    54: "npc_dota_hero_batrider",
    55: "npc_dota_hero_chen",
    56: "npc_dota_hero_spectre",
    57: "npc_dota_hero_ancient_apparition",
    58: "npc_dota_hero_doom_bringer",
    59: "npc_dota_hero_darkterror",
    60: "npc_dota_hero_furion",
    61: "npc_dota_hero_life_stealer",
    62: "npc_dota_hero_dark_seer",
    63: "npc_dota_hero_clinkz",
    64: "npc_dota_hero_huskar",
    65: "npc_dota_hero_huskar",
    66: "npc_dota_hero_treant",
    67: "npc_dota_hero_observer_ward",
    68: "npc_dota_hero_observer_ward",
    69: "npc_dota_hero_rubick",
    70: "npc_dota_hero_disruptor",
    71: "npc_dota_hero_silencer",
    72: "npc_dota_hero_obsidian_destroyer",
    73: "npc_dota_hero_lycan",
    74: "npc_dota_hero_brewmaster",
    75: "npc_dota_hero_shadow_demon",
    76: "npc_dota_hero_lone_druid",
    77: "npc_dota_hero_invoker",
    78: "npc_dota_hero_white_queen",
    79: "npc_dota_hero_troll_warlord",
    80: "npc_dota_hero_centaur",
    81: "npc_dota_hero_magnataur",
    82: "npc_dota_hero_shredder",
    83: "npc_dota_hero_bristleback",
    84: "npc_dota_hero_tusk",
    85: "npc_dota_hero_skywrath_mage",
    86: "npc_dota_hero_abaddon",
    87: "npc_dota_hero_elder_titan",
    88: "npc_dota_hero_terrorblade",
    89: "npc_dota_hero_phoenix",
    90: "npc_dota_hero_legion_commander",
    91: "npc_dota_hero_earth_spirit",
    92: "npc_dota_hero_abyssal_underlord",
    93: "npc_dota_hero_arc_warden",
    94: "npc_dota_hero_winter_wyvern",
    95: "npc_dota_hero_nyx_assassin",
    96: "npc_dota_hero_slark",
    97: "npc_dota_hero_medusa",
    98: "npc_dota_hero_underlord",
    99: "npc_dota_hero_monkey_king",
    100: "npc_dota_hero_dark_willow",
    101: "npc_dota_hero_pangolier",
    102: "npc_dota_hero_grimstroke",
    103: "npc_dota_hero_void_spirit",
    104: "npc_dota_hero_snapfire",
    105: "npc_dota_hero_mars",
    106: "npc_dota_hero_dawnbreaker",
    107: "npc_dota_hero_marci",
    108: "npc_dota_hero_primal_beast",
    109: "npc_dota_hero_muerta",
    110: "npc_dota_hero_faun",
    111: "npc_dota_hero_ogrmagician",
    112: "npc_dota_hero_revenant",
    113: "npc_dota_hero_puppet_master",
    114: "npc_dota_hero_magnus",
    115: "npc_dota_hero_ancestor",
    116: "npc_dota_hero_vagabond",
    117: "npc_dota_hero_radiance",
    118: "npc_dota_hero_satyr",
    119: "npc_dota_hero_oracle",
    120: "npc_dota_hero_void_tripper",
    121: "npc_dota_hero_mirror_fiend",
    122: "npc_dota_hero_netherdrake",
    123: "npc_dota_hero_apprentice",
    124: "npc_dota_hero_shadow_priest",
}

def get_hero_name(hero_id: int) -> str:
    """
    Convert numeric hero_id to Dota 2 hero name
    
    Args:
        hero_id: Numeric hero ID from Clarity parser
        
    Returns:
        Hero name string (e.g., "npc_dota_hero_pudge")
    """
    if hero_id in HERO_MAP:
        return HERO_MAP[hero_id]
    
    # Fallback for unknown IDs
    return f"npc_dota_hero_unknown_{hero_id}"
