"""Add steam_id to matches

Revision ID: 672850d57be6
Revises: 656d4a541eb8
Create Date: 2026-01-07 20:58:39.361209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '672850d57be6'
down_revision: Union[str, Sequence[str], None] = '656d4a541eb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('steam_id', sa.String(length=50), nullable=True))
    op.drop_index(op.f('ix_matches_match_id'), table_name='matches')
    op.create_index(op.f('ix_matches_match_id'), 'matches', ['match_id'], unique=False)
    op.create_index(op.f('ix_matches_steam_id'), 'matches', ['steam_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matches_steam_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_match_id'), table_name='matches')
    op.create_index(op.f('ix_matches_match_id'), 'matches', ['match_id'], unique=True)
    op.drop_column('matches', 'steam_id')
    # ### end Alembic commands ###
